# Populate a centos 6.5 box with
#
#   - aliyun mirrored yum repo
#   - mysql-server (5.1.73-5.el6_6.x86_64)

FROM ymattw/centos6-aliyun:latest
MAINTAINER Matthew Wang
RUN yum install -y mysql-server
